package org.voxelware.coretuff.Utility.Diagnostic;

import org.voxelware.coretuff.CoreTuff;
import org.voxelware.coretuff.api.diagnostics.DiagnosticProvider;
import org.voxelware.coretuff.internal.diagnostics.DiagnosticProviderRegistry;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;

public class DiagnosticDumpService {

    private static final DateTimeFormatter FILENAME_FMT = DateTimeFormatter.ofPattern("yyyy-MM-dd_HH-mm-ss");
    private static final DateTimeFormatter HEADER_FMT = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss Z");

    private final CoreTuff plugin;
    private final List<DiagnosticCollector> collectors = new ArrayList<>();
    private final ExceptionRingBuffer exceptionBuffer;
    private DiagnosticProviderRegistry providerRegistry;

    public DiagnosticDumpService(CoreTuff plugin, ExceptionRingBuffer exceptionBuffer) {
        this.plugin = plugin;
        this.exceptionBuffer = exceptionBuffer;
    }

    public void setProviderRegistry(DiagnosticProviderRegistry providerRegistry) {
        this.providerRegistry = providerRegistry;
    }

    public void registerCollector(DiagnosticCollector collector) {
        collectors.add(collector);
    }

    public DiagnosticResult generate() {
        List<String> lines = new ArrayList<>();
        String sep = "═══════════════════════════════════════════════════════════════════════";
        ZonedDateTime zdt = ZonedDateTime.now();
        String now = HEADER_FMT.format(zdt);
        String tz = ZoneId.systemDefault().getId();
        String version = plugin.getDescription().getVersion();

        lines.add(sep);
        lines.add("               CORETUFF DIAGNOSTIC DUMP");
        lines.add(sep);
        lines.add("");
        lines.add("Generated: " + now);
        lines.add("Timezone:  " + tz);
        lines.add("");

        for (DiagnosticCollector collector : collectors) {
            try {
                lines.add("--- " + collector.sectionName() + " ---");
                collector.collect(this, lines);
                lines.add("");
            } catch (Exception e) {
                lines.add("  [Collector error: " + e.getClass().getSimpleName() + "]");
                lines.add("");
            }
        }

        if (providerRegistry != null) {
            for (DiagnosticProvider provider : providerRegistry.getAll()) {
                try {
                    lines.add("--- " + provider.sectionName() + " ---");
                    String diagnose = provider.diagnose();
                    if (diagnose != null) {
                        lines.add(diagnose);
                    }
                    lines.add("");
                } catch (Exception e) {
                    lines.add("  [Provider error: " + e.getClass().getSimpleName() + "]");
                    lines.add("");
                }
            }
        }

        lines.add(sep);
        lines.add("End of CoreTuff Diagnostic Dump");
        lines.add("Generated by CoreTuff " + version);
        lines.add("Voxelware Studios");
        lines.add(sep);

        try {
            Path dir = plugin.getDataFolder().toPath().resolve("dumps");
            Files.createDirectories(dir);
            String filename = "dump-" + FILENAME_FMT.format(ZonedDateTime.now()) + ".txt";
            Path file = dir.resolve(filename);
            Files.write(file, lines);
            return new DiagnosticResult(true, file.toAbsolutePath().toString(), filename);
        } catch (IOException e) {
            plugin.getLogger().log(Level.SEVERE, "Failed to write diagnostic dump", e);
            return new DiagnosticResult(false, e.getMessage(), null);
        }
    }

    public ExceptionRingBuffer exceptionBuffer() {
        return exceptionBuffer;
    }

    public CoreTuff plugin() {
        return plugin;
    }

    public record DiagnosticResult(boolean success, String message, String filename) {}
}
